####################################################################
# Licensed Materials - Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2018-2026. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
version: '3.5'

services:
  wa-db2:
    env_file:
     - wa.env
    environment:
     - DB2INST1_PASSWORD=db2inst1 # Password for DB2 user (DO NOT TOUCH)
    build: ./db_tools
    ports: # port mapping "external:internal". Internal ports are predefined. 
     - "50000:50000" #DB2 port
    container_name: "wa-db2"
    privileged: true
    hostname: wa-db2
    networks:
     - wa-net
    volumes:
     - wa-db2inst1_home:/home/db2inst1/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
     
  wa-server:
    env_file:
     - wa.env
    environment:
     - DB_HOSTNAME=wa-db2 # The host name or IP address of database server (DO NOT TOUCH)
     - SERVERHOSTNAME=wa-server #  The host name on which the server is contacted by internal dynamic agents (DO NOT TOUCH)
     - SERVERPORT=31116 #  The port on which the server is contacted by internal dynamic agents (DO NOT TOUCH)     
     - CREATE_PLAN=true # If true, it executes an automatic JnextPlan at container deploy time
     - AGT_NAME=WA_SAGT # The name of the agent included in the server
     - SSL_PASSWORD= # Input the SSL Password for your custom certificates mounted on volume wa-certificates
    image: cp.icr.io/cp/ibm-workload-automation-server:10.2.4.00.20250423
    depends_on:
     - wa-db2
    ports: # port mapping "external:internal". Internal ports are predefined. 
     - "31116:31116" #HTTPS MASTER
     - "31111:31111" #NETMAN
     - "31131:31131" #EIF
    # - "35131:35131" #EIF SSL
    container_name: "wa-server"
    hostname: wa-server
    networks:
     - wa-net
    volumes:
     - wa-server-data:/home/wauser/
     - ./wa-certificates:/opt/wautils/certs # Mount the volume where custom SSL certificates need to be stored
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
     
  wa-console:
    env_file:
     - wa.env
    environment:
     - DB_HOSTNAME=wa-db2 # (DO NOT TOUCH)
     - ENGINE_HOSTNAME=wa-server # The host name or IP address of the engine (DO NOT TOUCH)
     - DB_NAME=DWC # For DB2/IDS/MSSQL is the name of console database. For ORACLE is the Oracle Service Name. Valid only for DB2/IDS/MSSQL/ORACLE
     - SSL_PASSWORD= # Input the SSL Password for your custom certificates mounted on volume wa-certificates
    image: cp.icr.io/cp/ibm-workload-automation-console:10.2.4.00.20250423
    depends_on:
     - wa-db2
    ports: # port mapping "external:internal". Internal ports are predefined. 
     - "9443:9443" #HTTPS DWC
    container_name: "wa-console"
    hostname: wa-console
    networks:
     - wa-net
    volumes:
     - wa-console-data:/home/wauser
     - ./wa-certificates:/opt/wautils/certs # Mount the volume where custom SSL certificates need to be stored
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        
        
  wa-ddm:
    platform: linux/amd64
    env_file:
     - wa-ddm.env
    environment:
     #- DB_HOSTNAME=wa-db2 # The host name or IP address of database server (DO NOT TOUCH)
     - SERVERHOSTNAME=wa-server #  The host name on which the server is contacted by internal dynamic agents (DO NOT TOUCH)
     - SERVERPORT=31116 #  The port on which the server is contacted by internal dynamic agents (DO NOT TOUCH)
     - HOSTNAME=wa-ddm # The fully qualified host name on which the server installation is running
     - PUBLIC_HOSTNAME=wa-ddm # The fully qualified host name or IP address on which the dynamic domain manager is contacted by the dynamic agent
     - DB_TYPE=POSTGRESQL # db2 | oracle
     - DB_USER=ddmuser
     - DB_PASSWORD=ddmpassword
     - DB_NAME=DDMDB # The name of IWS Database
     #- DB_PORT=50000 # The port of the database server
     - WLP_SEC_PORT=31116
     - WA_PASSWORD=wauser # The password of the user for which the component is installed
     - LICENSE_SERVER_ID=AAAAAAA
     - PUBLIC_PORT=33333
     - DWBNAME=WA_DWB_DDM # The bridge workstation name registered on the MDM
     - DDM_MASTER=WA_FTA # Master workstation name on MDM
     - DDM_DOMAIN=DYNAMICDM # The dynamic domain name
     - DDM_MDM_HOSTNAME=wa-server # MDM hostname reached by DDM
     - DDM_MDM_HTTPS_PORT=31116 # MDM HTTPS port reached by DDM
     - DATE_FORMAT=MM/DD/YYYY
     - WA_DEBUG=YES
     - SSL_PASSWORD=Hclrome00
    image: wa-registry.prod.hclpnp.com/wa-dev/ibm-workload-automation-ddm:10.2.8.00.amd64
    #image: ddm:fix
    privileged: true
    depends_on:
     - wa-postgres-ddm
    restart: "no"
    ports: # port mapping "external:internal". Internal ports are predefined.
     - "33333:31116" #HTTPS DDM
     - "41115:31115" #HTTPS MASTER
     - "41111:31111" #NETMAN
    container_name: "wa-ddm"
    hostname: wa-ddm
    networks:
     - wa-net
     
   

  wa-agent:
    env_file:
     - wa.env
    environment:
     - SERVERHOSTNAME=wa-server #  The host name of the server (DO NOT TOUCH)
     - SERVERPORT=31116 #  The port of the server (DO NOT TOUCH)    
     - SSL_PASSWORD= # Input the SSL Password for your custom certificates mounted on volume wa-certificates
    image: cp.icr.io/cp/ibm-workload-automation-agent-dynamic:10.2.4.00.20250423
    depends_on:
     - wa-server
    container_name: "wa-agent"
    hostname: wa-agent
    networks:
     - wa-net
    volumes:
      - wa-agent-data:/home/wauser
      - ./wa-certificates:/opt/wautils/certs # Mount the volume where custom SSL certificates need to be stored
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  wa-db2inst1_home:
  wa-server-data:
  wa-console-data:
  wa-agent-data:
  wa-ddm-data:
networks:
  wa-net:
    name: wa-net
